apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rhtap-e2e1 
  janus-idp.io/tekton: rhtap-e2e1
  backstage.io/kubernetes-id: rhtap-e2e1
  backstage.io/kubernetes-namespace: rhtap-e2e1 
  app.kubernetes.io/part-of: rhtap-e2e1
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  